import 'package:flutter/material.dart';
import 'shopping_item.dart';
import 'database.dart';

// Entry point of the app
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize the database
  final database =
  await $FloorAppDatabase.databaseBuilder('shopping_database.db').build();
  runApp(MyApp(database: database));
}

// Root widget of the application
class MyApp extends StatelessWidget {
  final AppDatabase database;

  const MyApp({super.key, required this.database});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Shopping List',
      home: Scaffold(
        appBar: AppBar(title: const Text("Shopping List")),
        body: ListPage(database: database),
      ),
    );
  }
}

// Stateful widget to manage the shopping list state
class ListPage extends StatefulWidget {
  final AppDatabase database;

  const ListPage({super.key, required this.database});

  @override
  ListPageState createState() => ListPageState();
}

class ListPageState extends State<ListPage> {
  // List to hold shopping items
  List<ShoppingItem> shoppingList = [];

  // Controllers to retrieve input from text fields
  final TextEditingController nameController = TextEditingController();
  final TextEditingController quantityController = TextEditingController();

  @override
  void initState() {
    super.initState();
    _loadItems();
  }

  Future<void> _loadItems() async {
    final items = await widget.database.shoppingDao.findAllShoppingItems();
    setState(() {
      shoppingList = items;
    });
  }

  // Add a new item to the list and database
  Future<void> _addItem() async {
    if (nameController.text.isNotEmpty && quantityController.text.isNotEmpty) {
      final newItem = ShoppingItem(
        null, // ID will be auto-generated by the database
        nameController.text,
        quantityController.text,
      );

      await widget.database.shoppingDao.insertShoppingItem(newItem);

      // Reload the full list from the database to get updated IDs etc
      await _loadItems();

      nameController.clear();
      quantityController.clear();
    }
  }

  // Delete an item from the list and database
  Future<void> _deleteItem(int index) async {
    final itemToDelete = shoppingList[index];

    await widget.database.shoppingDao.deleteShoppingItem(itemToDelete);

    await _loadItems();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        // Row for input fields and the Add button
        Padding(
          padding: const EdgeInsets.all(8.0),
          child: Row(
            children: [
              // Input for item name
              Expanded(
                child: TextField(
                  controller: nameController,
                  decoration: const InputDecoration(hintText: 'Item name'),
                ),
              ),
              const SizedBox(width: 8),
              // Input for item quantity
              Expanded(
                child: TextField(
                  controller: quantityController,
                  decoration: const InputDecoration(hintText: 'Quantity'),
                  keyboardType: TextInputType.number,
                ),
              ),
              const SizedBox(width: 8),
              // Button to add a new item
              ElevatedButton(
                onPressed: () async => await _addItem(),
                child: const Text('Add'),
              ),
            ],
          ),
        ),

        // Display the list of items or a message if empty
        Expanded(
          child: shoppingList.isEmpty
              ? const Center(child: Text("There are no items in the list"))
              : ListView.builder(
            itemCount: shoppingList.length,
            itemBuilder: (context, index) {
              return GestureDetector(
                // Long press to trigger delete confirmation
                onLongPress: () {
                  showDialog(
                    context: context,
                    builder: (context) => AlertDialog(
                      title: const Text("Delete Item"),
                      content: Text(
                          "Do you want to delete '${shoppingList[index].name}'?"),
                      actions: [
                        // Cancel deletion
                        TextButton(
                          child: const Text("No"),
                          onPressed: () => Navigator.of(context).pop(),
                        ),
                        // Confirm deletion
                        TextButton(
                          child: const Text("Yes"),
                          onPressed: () async {
                            await _deleteItem(index);
                            Navigator.of(context).pop();
                          },
                        ),
                      ],
                    ),
                  );
                },
                // Display each item
                child: Container(
                  alignment: Alignment.center,
                  padding: const EdgeInsets.symmetric(vertical: 4),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      // Item name
                      Text(
                        "${index + 1}: ${shoppingList[index].name}, ",
                        style: const TextStyle(fontSize: 16),
                      ),
                      const SizedBox(width: 10),
                      // Item quantity
                      Text(
                        "quantity: ${shoppingList[index].quantity}",
                        style: const TextStyle(fontSize: 16),
                      ),
                    ],
                  ),
                ),
              );
            },
          ),
        ),
      ],
    );
  }

  @override
  void dispose() {
    nameController.dispose();
    quantityController.dispose();
    super.dispose();
  }
}
